USE admin_users;
--ALTER DATABASE admin_users CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
--ALTER TABLE USER CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CREAR PROCEDIMIENTO ALMACENADO QUE REGISTA UN NUEVO USUARIO
DROP PROCEDURE IF EXISTS SP_USUARIO_REGISTRO;
CREATE PROCEDURE SP_USUARIO_REGISTRO(
    IN p_nombre VARCHAR(255) ,
    IN p_email VARCHAR(255),
    IN p_password VARCHAR(255)
)
BEGIN
    IF (SELECT COUNT(*) FROM USER WHERE email = p_email) = 0 THEN
        INSERT INTO USER ( NAME, EMAIL, PASSWORD, createdAt, updatedAt)
        SELECT p_nombre, p_email, p_password,  NOW(), NOW();
        SELECT 'Usuario registrado correctamente.' AS message;
    ELSE
        SELECT 'El correo ya está registrado. Por favor, elija otro correo.' AS message;
    END IF;
END;

-- LLAMAR AL PROCEDIMIENTO ALMACENADO
--CALL SP_USUARIO_REGISTRO('Jorgeww', 'JOdfddGE@MDefffreIIL.COM', '123456');


SELECT * FROM USER;


-- CREA EL SP PARA LISTAR LOS USUARIOS CREADOS
DROP PROCEDURE IF EXISTS SP_USUARIO_LISTAR;
CREATE PROCEDURE SP_USUARIO_LISTAR()
BEGIN
    SELECT ID, NAME, EMAIL, PASSWORD FROM USER;
END;

-- CREA SP PARA VERIFICAR SI EL EMAIL EXISTE
DROP PROCEDURE IF EXISTS SP_USUARIO_VERIFICAR_EMAIL;
CREATE PROCEDURE SP_USUARIO_VERIFICAR_EMAIL(
    IN p_email VARCHAR(255)
)
BEGIN
    SELECT COUNT(*) AS total FROM USER WHERE EMAIL = p_email;
END;